// Package image turns a blueprint's toolchain into a container image.
//
// This is where the cold-start strategy lives. Rather than running `mise
// install` when a sandbox boots — which costs minutes on every start and, on a
// metered provider, real money — the toolchain is baked into an image at build
// time. Booting a sandbox is then a registry pull, and the expensive install
// runs once per unique toolchain on whatever builder is cheapest.
package image

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"slices"
	"sort"
	"strings"
	"text/template"

	"github.com/chiragaggarwal/sbx/internal/blueprint"
)

const DefaultRepository = "sbx-base"

// Tag is the cache key for a built image. It hashes the *entire* build
// definition — the rendered Dockerfile and the baked mise.toml — not just the
// blueprint's toolchain. Keying on the toolchain alone means a change to the
// Dockerfile template silently reuses a stale image, which is a genuinely
// nasty bug: the blueprint looks correct and the sandbox behaves as if the fix
// were never applied.
func Tag(print *blueprint.Blueprint) (string, error) {
	dockerfile, err := Dockerfile(print)
	if err != nil {
		return "", err
	}
	digest := sha256.New()
	digest.Write([]byte(dockerfile))
	digest.Write([]byte{0})
	digest.Write([]byte(print.MiseConfiguration()))
	return hex.EncodeToString(digest.Sum(nil))[:16], nil
}

// Reference is the fully qualified image name for a blueprint. Two blueprints
// producing an identical build definition resolve to the same image, so the
// second one is free.
func Reference(registry string, print *blueprint.Blueprint) (string, error) {
	if print.Sandbox.Image != "" {
		return print.Sandbox.Image, nil
	}
	tag, err := Tag(print)
	if err != nil {
		return "", err
	}
	repository := DefaultRepository
	if registry != "" {
		repository = strings.TrimSuffix(registry, "/") + "/" + DefaultRepository
	}
	return repository + ":" + tag, nil
}

// dockerfileTemplate installs mise, bakes the blueprint's toolchain, and puts
// the mise shim directory on PATH. Shims are used rather than `mise activate`
// so that non-interactive `docker exec` and `ssh <host> <command>` resolve
// tools without sourcing a shell profile.
var dockerfileTemplate = template.Must(template.New("dockerfile").Parse(`# syntax=docker/dockerfile:1
# Generated by sbx — do not edit by hand.
FROM debian:bookworm-slim

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install --yes --no-install-recommends \
      {{ .AptPackages }} \
    && rm -rf /var/lib/apt/lists/*

# mise installs to ~/.local/bin; the shim directory is what makes tools
# resolvable from a non-login, non-interactive shell.
ENV MISE_DATA_DIR=/root/.local/share/mise
ENV PATH=/root/.local/share/mise/shims:/root/.local/bin:$PATH
RUN curl --fail --silent --show-error --location https://mise.run | sh \
    && mise --version

# The blueprint is installed as mise's *global* config rather than a
# directory-scoped one. Shims resolve a tool version by walking up from the
# current directory, so a project-scoped config would leave tools unresolvable
# anywhere outside that directory — including the repository the agent works in.
COPY mise.toml /root/.config/mise/config.toml

# Trust is required before mise will read a config it did not create, and the
# install is the one expensive step we are deliberately moving to build time.
RUN mise trust /root/.config/mise/config.toml \
    && mise install --yes \
    && mise reshim \
    && mise ls --installed

# A login shell sources /etc/profile, which resets PATH and would otherwise
# discard the ENV above. Re-export it here so interactive shell sessions
# resolve mise shims exactly like non-interactive exec does.
RUN printf '%s\n' \
      'export MISE_DATA_DIR=/root/.local/share/mise' \
      'export PATH=/root/.local/share/mise/shims:/root/.local/bin:$PATH' \
      > /etc/profile.d/10-sbx.sh \
    && chmod 0644 /etc/profile.d/10-sbx.sh

WORKDIR {{ .WorkingDirectory }}
CMD ["sleep", "infinity"]
`))

type templateData struct {
	AptPackages      string
	WorkingDirectory string
}

// basePackages are what every sandbox needs regardless of toolchain: enough to
// fetch mise, clone a repository, and let an agent look around.
var basePackages = []string{
	"bash", "ca-certificates", "curl", "git",
	"unzip", "xz-utils", "openssh-client", "procps",
}

// Dockerfile renders the build definition for a blueprint.
func Dockerfile(print *blueprint.Blueprint) (string, error) {
	var rendered bytes.Buffer
	packages := append(append([]string(nil), basePackages...), print.Sandbox.Packages...)
	sort.Strings(packages)
	data := templateData{
		AptPackages:      strings.Join(slices.Compact(packages), " "),
		WorkingDirectory: print.Sandbox.Repository.Directory,
	}
	if err := dockerfileTemplate.Execute(&rendered, data); err != nil {
		return "", fmt.Errorf("rendering dockerfile: %w", err)
	}
	return rendered.String(), nil
}

// Exists reports whether the image is already present locally, which is what
// makes a repeat `sbx up` fast.
func Exists(ctx context.Context, reference string) bool {
	command := exec.CommandContext(ctx, "docker", "image", "inspect", reference)
	return command.Run() == nil
}

// Build materialises the image for a blueprint. The build context is a
// temporary directory holding only the rendered Dockerfile and the minimal
// mise.toml, so the user's repository is never sent to the daemon.
func Build(ctx context.Context, reference string, print *blueprint.Blueprint, progress bool) error {
	directory, err := os.MkdirTemp("", "sbx-build-")
	if err != nil {
		return fmt.Errorf("creating build context: %w", err)
	}
	defer os.RemoveAll(directory)

	dockerfile, err := Dockerfile(print)
	if err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(directory, "Dockerfile"), []byte(dockerfile), 0o644); err != nil {
		return fmt.Errorf("writing dockerfile: %w", err)
	}
	if err := os.WriteFile(filepath.Join(directory, "mise.toml"), []byte(print.MiseConfiguration()), 0o644); err != nil {
		return fmt.Errorf("writing mise.toml: %w", err)
	}

	command := exec.CommandContext(ctx, "docker", "build", "--tag", reference, directory)
	if progress {
		command.Stdout = os.Stderr
		command.Stderr = os.Stderr
	}
	if err := command.Run(); err != nil {
		return fmt.Errorf("docker build %s: %w", reference, err)
	}
	return nil
}
